version: "3.9"
services:
  broker:
    image: rabbitmq:3
    ports:
      - "${DMTL_BROKER_PORT}:5672"
  tracking:
    build:
      dockerfile: mlflow.Dockerfile
      context: .
    ports:
      - "${DMTL_TRACKING_PORT}:5000"
    environment:
      - "BACKEND_STORE_URI=postgresql://mlflow:mlflow@tracking_db/mlflow"
    volumes:
      - "./lightning_data:/mlflow/artifacts"
  tracking_db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - ./mlflow_data:/var/lib/postgresql/data

