version: "3.9"
services:
  broker:
    image: rabbitmq:3
    ports:
      - "${DMTL_BROKER_PORT}:5672"
  tracking:
    build:
      dockerfile: mlflow.Dockerfile
      context: .
    ports:
      - "${DMTL_TRACKING_PORT}:5000"
    environment:
      - "BACKEND_STORE_URI=postgresql://mlflow:mlflow@tracking_db/mlflow"
    volumes:
      - "./lightning_data:/mlflow/artifacts"
  tracking_db:
    image: 'postgres:latest'

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: mlflow # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: mlflow # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: mlflow

