version: "3.9"
services:
  trainer:
    build:
      dockerfile: ./dml.Dockerfile
      context: .
    deploy:
      replicas: ${N_TRAINERS}
      resources:
        limits:
          cpus: '2'
    environment:
      - "BOOTSTRAP_SCRIPT=${BOOTSTRAP_SCRIPT}"
      - "BROKER_HOSTNAME=broker"
      - "BROKER_PORT=5672"
      - "N_DEVICES=1"
      - "DATASET=${DATASET}"
      - "TRAINER_THRESHOLD=${N_TRAINERS}"
      - "MODEL=${MODEL_NAME}"
      - "N_EPOCHS=${N_EPOCHS}"
      - "TRACKING_URI=http://tracking:5000"
      - "EXPERIMENT_NAME=${EXPERIMENT_NAME}"
      - "MAX_ROUND=${MAX_ROUND}"
      - "EXTRA_ARGS=${EXTRA_ARGS}"
    volumes:
      - "./data:/usr/src/app/data"
      - "./storage/models:/usr/src/app/out"
      - "./storage/logs:/usr/src/app/logs"
    depends_on:
      - broker
      - tracking
