TRAINING_MODULE = "training"

DATASET_PREPARE = f"{TRAINING_MODULE}.dataset.load"
NEXT_ROUND = f"{TRAINING_MODULE}.round.next"
ROUND_START = f"{TRAINING_MODULE}.round.start"
TRAIN_MODEL = f"{TRAINING_MODULE}.start"
MODEL_TRAINED = f"{TRAINING_MODULE}.completed"
EXPERIMENT_TEST = f"{TRAINING_MODULE}.test"
INIT_EXPERIMENT = f"{TRAINING_MODULE}.experiment.init"