HANDLER_MODULE = "handler"

HANDLER_START = f"{HANDLER_MODULE}.start"
HANDLER_STARTED = f"{HANDLER_MODULE}.started"
HANDLER_STOP = f"{HANDLER_MODULE}.stop"
HANDLER_STOPPED = f"{HANDLER_MODULE}.stopped"
